plugins:
    - jest
env:
    jest/globals: true
    browser: true
    node: true
    commonjs: true
    es2021: true
extends: eslint:recommended
parserOptions:
    ecmaVersion: latest
rules:
    indent:
        - error
        - tab
        # - 4
        # - space
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - always
